version: '3.8'

services:
  # PostgreSQL Database Only - Simplified
  postgres:
    image: postgres:15-alpine
    container_name: coding-contest-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: coding_contest_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d coding_contest_db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  postgres_data:
    driver: local
